spring:
  mvc:
    format:
      date: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false


logging:
  config: classpath:logback_pro.xml
server:
  servlet:
    encoding:
      charset: UTF-8
